const WinUIObject = require('./lib/object')

exports.DependencyObject = require('./lib/dependency-object')
exports.UIElement = require('./lib/ui-element')
exports.UIElementCollection = require('./lib/ui-element-collection')
exports.FrameworkElement = require('./lib/framework-element')
exports.Panel = require('./lib/panel')
exports.Canvas = require('./lib/canvas')
exports.TextBlock = require('./lib/text-block')
exports.FontFamily = require('./lib/font-family')
exports.Brush = require('./lib/brush')
exports.SolidColorBrush = require('./lib/solid-color-brush')
exports.WebView2 = require('./lib/web-view2')
exports.Window = require('./lib/window')

exports.Compositor = require('./lib/compositor')
exports.CompositionObject = require('./lib/composition-object')
exports.Visual = require('./lib/visual')
exports.ContainerVisual = require('./lib/container-visual')
exports.ShapeVisual = require('./lib/shape-visual')
exports.CompositionShape = require('./lib/composition-shape')
exports.CompositionShapeCollection = require('./lib/composition-shape-collection')
exports.CompositionSpriteShape = require('./lib/composition-sprite-shape')
exports.CompositionGeometry = require('./lib/composition-geometry')
exports.CompositionRoundedRectangleGeometry = require('./lib/composition-rounded-rectangle-geometry')
exports.CompositionBrush = require('./lib/composition-brush')
exports.CompositionColorBrush = require('./lib/composition-color-brush')
exports.CompositionClip = require('./lib/composition-clip')
exports.CompositionGeometricClip = require('./lib/composition-geometric-clip')
exports.ElementCompositionPreview = require('./lib/element-composition-preview')

exports.PackageManager = require('./lib/package-manager')

require('./lib/handle').expose(
  Object.values(exports).filter((Class) => Class.prototype instanceof WinUIObject)
)
