const binding = require('../binding')

exports.POINTER_DEVICE_TYPE_TOUCH = binding.POINTER_DEVICE_TYPE_TOUCH
exports.POINTER_DEVICE_TYPE_PEN = binding.POINTER_DEVICE_TYPE_PEN
exports.POINTER_DEVICE_TYPE_MOUSE = binding.POINTER_DEVICE_TYPE_MOUSE
